version: '3.8'
  
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      new:
        aliases:
          - mongo

  # DESCOMENTE ESSA LINHA CASO QUEIRA RODAR A API TAMBÉM NO DOCKER
  
  # api:
  #   container_name: api
  #   image: api
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: .
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - new

networks:
  new:  